CREATE TABLE IF NOT EXISTS job_listings (
                                            id INTEGER PRIMARY KEY AUTOINCREMENT,
                                            title TEXT NOT NULL,
                                            company TEXT NOT NULL,
                                            company_url TEXT NOT NULL,
                                            location TEXT NOT NULL,
                                            description TEXT NOT NULL,
                                            remote_allowed BOOLEAN NOT NULL,
                                            job_state TEXT NOT NULL,
                                            company_size TEXT NOT NULL,
                                            company_size_score INTEGER NOT NULL,
                                            job_url TEXT UNIQUE NOT NULL,
                                            date TEXT NOT NULL,
                                            listed_at INTEGER NOT NULL,
                                            applicants_count INTEGER,
                                            skills_match REAL,
                                            model_fit_score REAL,
                                            preliminary_score REAL,
                                            success_probability REAL,
                                            role_complexity REAL,
                                            effort_days_to_fit REAL,
                                            critical_skill_mismatch_penalty REAL,
                                            experience_gap REAL,
                                            areas_for_development TEXT,
                                            reasoning TEXT,
                                            overall_relevance REAL DEFAULT 0.0,
                                            last_checked INTEGER,
                                            last_reranked INTEGER,
                                            is_posted INTEGER DEFAULT 1,
                                            application_status TEXT DEFAULT 'not applied',
                                            scoring_model TEXT
);
