CREATE TABLE IF NOT EXISTS blacklist (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    type TEXT NOT NULL,
    value TEXT NOT NULL,
    reason TEXT,
    date_added TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(type, value)
)
